#!/usr/bin/bash
for i in *.mkv
do	
	flag=0
	d=$i
	#echo $i
	if [[ $d == *\[* ]] || [[ $d == *\(* ]]; then	
		d=$(echo $d | sed 's/\[[^]]*\]//g' | sed 's/([^)])//g' | sed 's/[(][^)]*[)]//g')
		d=$(echo $d | sed -r 's/ .mkv/.mkv/g')
		flag=1
	fi
	if [[ $d == *0* ]]; then
		d=$(echo $d | sed -r 's/(\ )+0+([0-9]+)/ \2/g')
	fi
	if [[ flag -eq 1 ]]; then
		echo -n "$(tput bold)$(tput setaf 14)$i --> $d$(tput sgr0)"
		[[ $# -ne 0 ]] && ffmpeg -loglevel quiet -stats -i "$i" -n -map 0 -c copy -c:v:0 libx265 -crf 28 -map_metadata 0 "./TBW/$d"
	else
		echo "$(tput bold)$(tput setaf 14)$i$(tput sgr0)"
		[[ $# -ne 0 ]] && ffmpeg -loglevel quiet -stats -i "$i" -n -map 0 -c copy -c:v:0 libx265 -crf 28 -map_metadata 0 "./TBW/$d"
	fi
	echo	

done
